INFO - 2025-08-06 17:54:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:54:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:54:45 --> Usuario autenticado con role_id: 
INFO - 2025-08-06 17:54:45 --> Usuario autenticado con role_id: 
INFO - 2025-08-06 17:54:57 --> El mÃ©todo authenticate fue llamado
INFO - 2025-08-06 17:54:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:54:58 --> Usuario autenticado: Admin Principal
INFO - 2025-08-06 17:54:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:55:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:55:13 --> UserManagementModel: getUsers called with id: 
ERROR - 2025-08-06 17:55:13 --> mysqli_sql_exception: Unknown column 'users.id_user' in 'field list' in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`....', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\laragon\www\SIARES\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\SIARES\app\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\SIARES\app\Controllers\ProfileController.php(13): App\Models\UserManagementModel->getUsers(NULL)
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\ProfileController->index()
#9 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProfileController))
#10 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 17:55:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
[Method: GET, Route: admin/profile]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\ProfileController.php(13): App\Models\UserManagementModel->getUsers(null)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProfileController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProfileController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:55:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\ProfileController.php(13): App\Models\UserManagementModel->getUsers(null)
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProfileController->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProfileController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:55:13 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\ProfileController.php(13): App\Models\UserManagementModel->getUsers(null)
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ProfileController->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProfileController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-08-06 17:55:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 17:55:31 --> UserManagementModel: getUsers called with id: 
ERROR - 2025-08-06 17:55:31 --> mysqli_sql_exception: Unknown column 'users.id_user' in 'field list' in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`....', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\laragon\www\SIARES\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\SIARES\app\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\SIARES\app\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
#9 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
#10 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 17:55:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
[Method: GET, Route: admin/usermanagement]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:55:31 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 17:55:31 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-08-06 21:59:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 21:59:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 21:59:43 --> Usuario autenticado con role_id: 
INFO - 2025-08-06 22:00:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:00:12 --> Usuario autenticado con role_id: 
INFO - 2025-08-06 22:00:39 --> El mÃ©todo authenticate fue llamado
INFO - 2025-08-06 22:00:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:00:39 --> Usuario autenticado: Admin Principal
INFO - 2025-08-06 22:00:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:01:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:01:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:01:22 --> UserManagementModel: getUsers called with id: 
ERROR - 2025-08-06 22:01:22 --> mysqli_sql_exception: Unknown column 'users.id_user' in 'field list' in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`....', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`....')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`....')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`....', Array, false)
#4 C:\laragon\www\SIARES\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\system\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\SIARES\app\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\SIARES\app\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
#9 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
#10 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-08-06 22:01:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
[Method: GET, Route: admin/usermanagement]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:01:22 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 7 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:01:22 --> [Caused by] mysqli_sql_exception: Unknown column 'users.id_user' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = \'ADMIN\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `users`.`id_user`, `users`.`name`, `users`.`last_name`, `users`.`identification`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`status`, `users`.`login_attempts`, `users`.`last_login_attempt`, `users`.`role_id`, `users`.`date_registration`, `users`.`profile_image`, `roles`.`role_name`
FROM `users`
JOIN `roles` ON `roles`.`id_role` = `users`.`role_id`
WHERE `roles`.`role_name` = :roles.role_name:', [...], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Models\UserManagementModel.php(34): CodeIgniter\BaseModel->findAll()
 8 APPPATH\Controllers\UserManagementController.php(22): App\Models\UserManagementModel->getUsers()
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UserManagementController->index()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserManagementController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-08-06 22:03:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:03:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-08-06 22:03:54 --> mysqli_sql_exception: Table 'siares.requests' doesn't exist in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_...', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_...')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_...')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_...', Array, false)
#4 C:\laragon\www\SIARES\app\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\app\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
#6 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
#7 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-06 22:03:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
[Method: GET, Route: admin/pqrsmanagement]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 2 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:03:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 4 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:03:54 --> [Caused by] mysqli_sql_exception: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 5 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-08-06 22:03:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:03:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-08-06 22:03:54 --> mysqli_sql_exception: Table 'siares.requests' doesn't exist in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_...', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_...')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_...')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_...', Array, false)
#4 C:\laragon\www\SIARES\app\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\app\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
#6 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
#7 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-06 22:03:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
[Method: GET, Route: admin/pqrsmanagement]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 2 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:03:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 4 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:03:54 --> [Caused by] mysqli_sql_exception: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 5 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2025-08-06 22:22:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-08-06 22:22:40 --> Usuario autenticado con role_id: 1
INFO - 2025-08-06 22:22:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-08-06 22:22:40 --> mysqli_sql_exception: Table 'siares.requests' doesn't exist in C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\SIARES\system\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_...', 0)
#1 C:\laragon\www\SIARES\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_...')
#2 C:\laragon\www\SIARES\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_...')
#3 C:\laragon\www\SIARES\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_...', Array, false)
#4 C:\laragon\www\SIARES\app\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\SIARES\app\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
#6 C:\laragon\www\SIARES\system\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
#7 C:\laragon\www\SIARES\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
#8 C:\laragon\www\SIARES\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\SIARES\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\SIARES\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\SIARES\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-08-06 22:22:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
[Method: GET, Route: admin/pqrsmanagement]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 2 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:22:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 4 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-08-06 22:22:40 --> [Caused by] mysqli_sql_exception: Table 'siares.requests' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT `r`.`id_request`, `r`.`unique_code`, `u`.`email`, `rt`.`id_type`, `rt`.`name` as `type`, `rs`.`id_status`, `rs`.`name` as `status`, `r`.`attachment_url`, `r`.`description`, `r`.`response`, `r`.`created_at`, `r`.`updated_at`
FROM `requests` `r`
JOIN `request_statuses` `rs` ON `r`.`status_id` = `rs`.`id_status`
JOIN `request_types` `rt` ON `r`.`type_id` = `rt`.`id_type`
JOIN `users` `u` ON `r`.`user_id` = `u`.`id_user`', [], false)
 5 APPPATH\Models\PqrsManagementModel.php(48): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\PqrsManagementController.php(21): App\Models\PqrsManagementModel->getDetailedRequests()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PqrsManagementController->index()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PqrsManagementController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
